[package]
name = "lula-lang"
version = "0.1.0"
authors = ["Suirabu <42366259+Bryce101189@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
